apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-database
  namespace: snacktime-recipes
spec:
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
