apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-database
spec:
  storageClassName: {{ $.Values.storage.storageClassName }}
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
