name: Run Tests
on: [push]
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Install backend packages
        run: cd apps/backend && npm install
      - name: Run tests
        run: npx nx test backend