name: Run Tests
on: [push]

env:
  PORT: 3333
  HOST: 0.0.0.0
  NODE_ENV: development
  APP_KEY: 9UaTGJZqlVe6AFawap6p87TKEx-8XuxN
  DRIVE_DISK: local
  DB_CONNECTION: sqlite
  SESSION_DRIVER: cookie

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Install backend packages
        run: cd apps/backend && npm install
      - name: Migrating database
        run: cd apps/backend && node ace migration:run
      - name: Seeding database
        run: cd apps/backend && node ace db:seed
      - name: Run tests
        run: npx nx test backend